# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

 
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:   
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '77.0.3865.40'
    - run: wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - run: unzip ~/chromedriver_linux64.zip -d ~/
    - run: rm ~/chromedriver_linux64.zip
    - run: sudo mv -f ~/chromedriver /usr/local/share/
    - run: sudo chmod +x /usr/local/share/chromedriver
    - run: sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - run: yarn && yarn bootstrap
    - name: Test on Chrome Headless and with Playwright Browsers
      run: yarn test
 
